### ISSUE TITLE
Does this require ace permissions? 

### ISSUE THREAD

**Issue by Kalizar86** [Disabled-Coding/dc-adminmenu#2]
I installed it but when I use it I get kicked and it says "How are you able to do this?"  I have myself added as an admin in txadmin.

**Comment by ChatDisabled** [comment]
Did you add yourself as an admin in your server.cfg though? The txAdmin perms and QBCore perms are separate.

**Comment by ChatDisabled** [comment]
When I first responded was on my phone so I didn't see the title. But yes this is meant for the newest QBCore with the ace permissions. The older permission system works just as well since it uses the built in functions to check your permissions. Only functions that won't work are the ones that utilizes the `PermOrder` function. Which I had to change to do some hackery to actually work with the newest QBCore _sigh_. There will be an update in the future to have a config option for either new or old perm system to change `PermOrder` behaviour.

And again txAdmin is indeed different from the QBCore permissions system. Both old and new. E.g. new one works like this in my case `add_principal identifier.fivem:1070255 qbcore.god`. Old one is simply adding yourself in your database.

**Comment by Vuxified** [comment]
how would I find my identifer for fivem?

**Comment by ChatDisabled** [comment]
> how would I find my identifer for fivem?

Can be any identifier that is linked to your account connecting to the server at that time. But again when first setting up a QBCore server everything is already setup for you. https://forum.cfx.re/t/ace-permissions/107706/7

**Comment by ChatDisabled** [comment]
@Vuxified @Kalizar86 Is there anything else? Or can this be closed?
